projects:
  feed:
    schema: feed.schema.graphql
    include: src/docs/feed/**/*.graphql
    extensions:
      endpoints:
        Default GraphQL Endpoint:
          url: https://thegraph.onchainfeed.org/subgraphs/name/azuro-protocol/azuro-data-feed-polygon-amoy-dev
          headers:
            user-agent: JS GraphQL
          introspect: false
  bets:
    schema: bets.schema.graphql
    include: src/docs/bets/**/*.graphql
    extensions:
      endpoints:
        Default GraphQL Endpoint:
          url: https://thegraph.azuro.org/subgraphs/name/azuro-protocol/azuro-api-polygon-amoy-dev-v3
          headers:
            user-agent: JS GraphQL
          introspect: false
  legacy-live-feed:
    schema: live.schema.graphql
    include: src/docs/legacy-live-feed/**/*.graphql
    extensions:
      endpoints:
        Protocol:
          url: https://thegraph.azuro.org/subgraphs/name/azuro-protocol/azuro-api-live-data-feed-preprod
          headers:
            user-agent: JS GraphQL
          introspect: false
